### ISSUE TITLE
Elevator 1

### ISSUE THREAD

**Issue by 1000DollarBill** [chopshop-166/frc-2018#35]
- [x] Can it move up and down?

- [x] Brake

- [x] Limit Switches

**Comment by 1000DollarBill** [comment]
Motors work, and they work correctly!

**Comment by 1000DollarBill** [comment]
Limit switches do stop the elevator

**Comment by bot190** [comment]
We have brake control but the limit switches were having trouble at SE MA for some reason. Hopefully this functionality has been fixed.

**Comment by bot190** [comment]
Closing this as competitions are over
