### ISSUE TITLE
Drive

### ISSUE THREAD

**Issue by bot190** [chopshop-166/frc-2018#4]
### Functions
* read gyro
* read proximity sensors
* set motors to speed
* read encoders
* create a PID controller for gyro

### Commands
* drive with joysticks (arcade drive!)
* drive straight
* drive a specified distance
* turn a specified angle
* drive until close to something

**Comment by dlaflotte** [comment]
Allow the Drive stop to be limited by the Lidar

**Comment by bot190** [comment]
Closing this as competitions are over
