### ISSUE TITLE
Enhance Lidar Support

### ISSUE THREAD

**Issue by dlaflotte** [chopshop-166/frc-2018#9]
- [x] Add Filter for Noise
- [x] Allow to convert to in from mm
- [x] Allow for changing of all modes supported by TinyLidar
- [x] Clean up misspellings and unused imports in code (ie BUSS, clean imports)
- [x] Merge into master

**Comment by JoshLaflotte** [comment]
#4 fixed

**Comment by bot190** [comment]
- [x] Implement PIDSource
- [x] Add support for other I2C commands

**Comment by bot190** [comment]
Added a method to change modes and query the settings. Added a filter for the values, as well as a test of validity of the data.
